import { Injectable } from '@angular/core';
import { Foods } from 'src/app/shared/models/food';
import { Tag } from 'src/app/shared/models/tag';

@Injectable({
  providedIn: 'root',
})
export class FoodService {
  constructor() {}

  getFoodById(id: number): Foods {
    return this.getAll().find((food) => food.id == id)!;
  }
  getAllFoodsByTag(tag: string): Foods[] {
    return tag === 'All'
      ? this.getAll()
      : this.getAll().filter((food) => food.tags?.includes(tag));
  }

  getAllTags(): Tag[] {
    return [
      { name: 'All' },
      { name: 'FastFood' },
      { name: 'Pizza' },
      { name: 'Lunch' },
      { name: 'SlowFood' },
      { name: 'Fry' },
      { name: 'Soup' },
      { name: 'IceCream' },
    ];
  }

  getAll(): Foods[] {
    return [
      {
        id: 1,
        name: 'Salad',
        cookTime: '10-20',
        price: 10,
        origins: ['Italy'],
        imageUrl: 'assets/card1.jpg',
        tags: ['SlowFood'],
      },
      {
        id: 2,
        name: 'Malai Kofta',
        cookTime: '5-10',
        price: 8,
        origins: ['USA'],
        imageUrl: 'assets/c3.webp',
        tags: ['Lunch'],
      },
      {
        id: 3,
        name: 'Pancake',
        cookTime: '15-25',
        price: 20,
        origins: ['Japan'],
        imageUrl: 'assets/c4.jpg',
        tags: ['Healthy', 'SlowFood'],
      },
      {
        id: 4,
        name: 'Burgur Fries',
        cookTime: '20-30',
        price: 12,
        origins: ['Italy'],
        imageUrl: 'assets/c5.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id: 5,
        name: 'Potatato Fry',
        cookTime: '5-15',
        price: 7,
        origins: ['Global'],
        imageUrl: 'assets/c6.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id: 6,
        name: 'Chole kulcha',
        cookTime: '10-20',
        price: 9,
        origins: ['Mexico'],
        imageUrl: 'assets/c7.jpg',
        tags: ['FastFood', 'Lunch'],
      },
      {
        id: 7,
        name: 'Rapen Ramen',
        cookTime: '15-25',
        price: 14,
        origins: ['Japan'],
        imageUrl: 'assets/c8.webp',
        tags: ['Healthy', 'Lunch'],
      },
      {
        id: 8,
        name: 'Burgur Chicken',
        cookTime: '20-30',
        price: 25,
        origins: ['USA'],
        imageUrl: 'assets/c9.jpg',
        tags: ['FastFood','Dinner'],
      },
      {
        id: 9,
        name: 'Mint Ice Cream',
        cookTime: '5-10',
        price: 5,
        origins: ['Global'],
        imageUrl: 'assets/c10.jpg',
        tags: ['IceCream'],
      },
      {
        id: 10,
        name: 'Hakka Noodles',
        cookTime: '5-15',
        price: 6,
        origins: ['Global'],
        imageUrl: 'assets/c11.avif',
        tags: ['FastFood'],
      },
      {
        id: 11,
        name: 'Momos',
        cookTime: '15-25',
        price: 13,
        origins: ['USA'],
        imageUrl: 'assets/c12.jpg',
        tags: ['FastFood', 'Dinner'],
      },
      {
        id: 12,
        name: 'Spring Rolls',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c13.jpg',
        tags: ['FastFood', 'Snack'],
      },
      {
        id: 13,
        name: 'Masala Fries',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c14.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id: 14,
        name: 'Shahi Paneer',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c15.jpg',
        tags: ['Lunch'],
      },
      {
        id: 15,
        name: 'chicken Fried Rice',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c16.jpg',
        tags: ['Lunch', 'Fry'],
      },
      {
        id: 16,
        name: 'Onion Pizza',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c17.jpg',
        tags: ['FastFood', 'Pizza'],
      },
      {
        id: 17,
        name: 'Margherita Pizza',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c18.jpg',
        tags: ['FastFood', 'Pizza'],
      },
      {
        id: 18,
        name: 'Black Bean Pizza',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c19.jpg',
        tags: ['FastFood', 'Pizza'],
      },
      {
        id: 19,
        name: 'Mashroom Pizza',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c20.jpg',
        tags: ['FastFood', 'Pizza'],
      },
      {
        id: 20,
        name: 'Beens',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c21.jpg',
        tags: ['SlowFood'],
      },
      {
        id: 21,
        name: 'Brown beans',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c22.webp',
        tags: ['SlowFood'],
      },
      {
        id: 22,
        name: 'Potato fish',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c23.jpg',
        tags: ['FastFood', 'Snack'],
      },
      {
        id: 23,
        name: 'Snacks balls',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c24.jpg',
        tags: ['SlowFood', 'Snack'],
      },
      {
        id: 24,
        name: 'Minni Rolls',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c25.webp',
        tags: [ 'Snack'],
      },
      {
        id: 25,
        name: 'Potato Chips',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c26.png',
        tags: ['Snack'],
      },
      {
        id: 26,
        name: 'Red valley',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c27.jpg',
        tags: ['IceCream'],
      },
      {
        id: 27,
        name: 'Strawberry Ice Cream',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c28.webp',
        tags: ['IceCream'],
      },
      {
        id: 28,
        name: 'Chocolate Ice Cream',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c29.jpg',
        tags: ['IceCream'],
      },
      {
        id: 29,
        name: 'Chocolate Rolls',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c30.jpg',
        tags: ['IceCream'],
      },
      {
        id: 30,
        name: 'vegetable Soup',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c31.jpg',
        tags: ['Soup'],
      },
      {
        id: 31,
        name: 'Thukpa Soup',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c32.jpg',
        tags: ['Soup'],
      },
      {
        id: 32,
        name: 'Pasta soup',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c33.png',
        tags: ['Soup'],
      },
      {
        id: 33,
        name: 'Brokoli soup',
        cookTime: '10-20',
        price: 7,
        origins: ['USA'],
        imageUrl: 'assets/c34.jpg',
        tags: ['Soup'],
      },
      
      
    ];
  }
}
